name: Validate Azure link

on:
  workflow_dispatch:
    inputs:
      environment_name:
        description: "Environment name"
        required: true
permissions:
  contents: read
  issues: write
jobs:
  link-azure:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the code
        uses: actions/checkout@v4
      - name: Validate Azure Credentials
        run: |
          function missing_secret {
            echo "::error::To continue, we need to have Azure credentials set. Please set them and try again."
            exit 1
          }

          if [[ -z "${{ secrets.AZURE_CLIENT_ID }}" ]] \
            || [[ -z "${{ secrets.AZURE_CLIENT_SECRET }}" ]] \
            || [[ -z "${{ secrets.AZURE_TENANT_ID }}" ]] \
            || [[ -z "${{ secrets.AZURE_SUBSCRIPTION_ID }}" ]]; then
            missing_secret
          fi

          az login --service-principal \
            --username ${{ secrets.AZURE_CLIENT_ID }} \
            --password=${{ secrets.AZURE_CLIENT_SECRET }} \
            --tenant ${{ secrets.AZURE_TENANT_ID }} \
            --output none

          if [ $? -ne 0 ]; then
            missing_secret
          fi

          az account set --subscription ${{ secrets.AZURE_SUBSCRIPTION_ID }}

          if [ $? -ne 0 ]; then
            missing_secret
          fi

          # If both the client-id and client-secret for the web-app are set, let's test these credentials
          if [[ -n "${{ secrets.APP_REGISTRATION_APP_ID }}" ]] \
            && [[ -n "${{ secrets.WEB_APP_CLIENT_SECRET }}" ]]; then

              az login --service-principal \
              --username ${{ secrets.APP_REGISTRATION_APP_ID }} \
              --password=${{ secrets.WEB_APP_CLIENT_SECRET }} \
              --tenant ${{ secrets.AZURE_TENANT_ID }} \
              --output none

              if [ $? -ne 0 ]; then
                missing_secret
              fi

              az account set --subscription ${{ secrets.AZURE_SUBSCRIPTION_ID }}

              if [ $? -ne 0 ]; then
                missing_secret
              fi
          fi
        env:
          GH_TOKEN: ${{ github.token }}
